### ISSUE TITLE
[FEAT] Hot restart using R in console

### ISSUE THREAD

**Issue by mahmoudajawad** [erickzanardo/dashmon#1]
Thanks for this tool, this already saves a lot of my time, not needing to do hot-reload manually. And, while it is doing exactly what it advertise, I'm needing hot-restart as otherwise the only way to do so is to stop dashmon and re-run it.

Could you please consider implementing hot-restart using R, or any other method you might come across?

**Comment by erickzanardo** [comment]
Published in `0.0.2`
